# Paths & Storage
dataset_name: "HuggingFaceH4/ultrafeedback_binarized"
model_name: "ibm-granite/granite-4.0-350m"
experiment_name: "granite-ultrafeedback"
run_name: "assistant_only_loss_experiment_with"

sample_num: 200


lora:
    use_lora: True
    lora_rank: 16
    lora_alpha: 32
    target_modules: "all-linear"

training:
    # Training Parameters
    num_train_epochs: 2
    max_steps: -1
    assistant_only_loss: True  # Requires patched chat template
    add_generation_prompt: False  # Should be set to False for training
    learning_rate: 5.0e-6
    lr_scheduler_type: "cosine"
    warmup_steps: 50
    max_grad_norm: 5.0

    # Batch Size & DataLoading
    per_device_train_batch_size: 4
    gradient_accumulation_steps: 8
    dataloader_num_workers: 4
    packing: True
    packing_strategy: "wrapped"  # "bfd" throws away overflow tokens, "bfd_split" splits longer into chunks, "wrapped" all tokens are concatenated into a stream and split into a fixed-length blocks
    padding_side: "right"  # need to be left for GRPO (does generation)

    # Logging
    logging_steps: 10
    save_steps: 200
    eval_strategy: "steps"
    eval_steps: 20
    report_to: ["mlflow"]
    output_dir: "/storage/granite-sft-train/lr_5e-6_1_grad_clip_assist_only"

inference:
    padding_side: "left"